### ISSUE TITLE
Cukes does not suport complex regex expressions

### ISSUE THREAD

**Issue by annapuskarjova** [ctco/cukes-rest#20]
When I try to verify the value 255

  Scenario: test
    When the client performs GET request on api/contracts/-1
    Then status code is 200
    And response contains property "sections[?(@.sectionId == -1)].coveredGeoscopes[?(@.coveredGeoscope == 255)].coveredGeoscope" with value "255"

cukes give an error:
java.lang.IllegalArgumentException: Invalid JSON expression:
Script1.groovy: 1: expecting EOF, found '[' @ line 1, column 35.
                            sections[?(@.sectionId == -1)].coveredGeoscopes[?(@.coveredGeoscope == 255)].coveredGeoscope
                                     ^

but when I use the same query in http://jsonpath.herokuapp.com/

it easily find the needed value.
JSON file I can send by e-mail if needed.

**Comment by anatolijs-antonovs** [comment]
Not an issue, because RestAssured use Groovy's Gpath instead of Jayway's JsonPath.
Gpath function "find" can be used to locate some elements in the array, for example:
`And response contains property "sections.find{it.sectionId == -1}.coveredGeoscopes.find{it.coveredGeoscope == 255}.coveredGeoscope" with value "255".`
More details can be found in documentation: [http://groovy-lang.org/processing-xml.html#_gpath](url)

**Comment by AlexeyBuzdin** [comment]
Closed, since agreed that this is not an issue
