### ISSUE TITLE
Add CI tool integration

### ISSUE THREAD

**Issue by AlexeyBuzdin** [ctco/cukes-rest#3]
Add either https://snap-ci.com/ or https://travis-ci.org/ integration.

Should have:
- Post Submit: 
  - Run Tests 
  - Publish Snapshot version
- Deploy version
  - Increment version
  - Deploy to MVN Central

**Comment by Quesar** [comment]
'Post Submit' part has been set up on Snap-CI -- https://snap-ci.com/ctco/cukes-rest/branch/master

**Comment by Quesar** [comment]
Manually triggerable 'Publish version' pipeline step has been set up and used to release version 0.2.0 .
After Sonatype will enable automatic synchronization to Maven central nexus-staging-maven-plugin will have to be set up so that the releases would not require manual actions to forward artifacts from staging repository to release repository.

**Comment by Quesar** [comment]
Deployment has been set up with nexus-staging-maven-plugin.
Release of version 0.2.1 was performed with the new configuration.
