### ISSUE TITLE
Wonder how to create integer variable or other kinds of variables instead of string type via GlobalWorld

### ISSUE THREAD

**Issue by aovercome1234** [ctco/cukes-rest#31]
``` java
@Singleton
class GlobalWorld {

    private final Map<String, String> context = new ConcurrentHashMap<String, String>(); //Source code

    private final Map<String, Object> context = new ConcurrentHashMap<String, Object>(); //wanta it like this
```

Example:
GivenSteps:

``` java
@Given("^let variable \"([^\"]+)\" equal to \"([^\"]+)\"$")
    public void var_assigned(String varName, String value) {
        world.put(varName, value);
    } // ----------------------------------------------------------------------------source code
```

wanta it support like this

``` java
@Given("^let variable \"([^\"]+)\" equal to (\\d+)$")
    public void var_assigned(String varName, int value) {
        world.put(varName, value);
    }
```

And then in the feature file as below:

``` gherkin
  Scenario: add highseas demo
    Given let variable "intVal" equal to 123
    Given request body "{"age":{(age)}}"
```

 I can get the integer value via `{(age)}` instead of the string type

**Comment by AlexeyBuzdin** [comment]
Had a prototype with Object in GlobalWorld, but then you end up with all kind of Double/Float comparison problems.

Do you experience problem with?

``` gherkin
Scenario: add highseas demo
Given let variable "intVal" equal to 123
Given request body "{"age":{(age)}}"
```

{(age)} will be inflated as Java String type, but in the JSON it will end up as number. Since you don't have any quotes for age in the JSON

**Comment by aovercome1234** [comment]
@AlexeyBuzdin 
yes, I agree with you very much. But when using this with DataTable, the table will transfer all the values into string type, take an example as below:

``` gherkin
Scenario: prac intVal with dataTable 
    Given let variable "intVal" equal to "123"
    Given request body as below 
     |val|
     |{(intVal)}|
```

print the request body: 
actual is: `{"val":"123"}`
but I want it as `{"val":123}`

Have you considered such a scenario with lots of params as below?

``` gherkin
Given request body as below 
     |val1         |val2         |val3        |val4         |val5         |val6         |val7         |val8        |
     | {(intVal)} | {(intVal)} |{(intVal)} | {(intVal)} | {(intVal)} | {(intVal)} | {(intVal)} | {(intVal)} |
```

I try to change source code according by my own requirement with adding some flags as "(int)", but I  failed, please give me some good ideas or suggestions, thanks so much. 

``` gherkin
Given request body as below 
     |val1               |val2                |val3              |val4               |val5               |val6               |
     | {(intVal)}(int) | {(intVal)}(int) |{(intVal)}(int) | {(intVal)}(int) | {(intVal)}(int) | {(intVal)}(int) | 
```

**Comment by AlexeyBuzdin** [comment]
Hi, thanks, that's a valid point, will look into this. 

Also maybe `Given request body from file /myfile.json` will be a good substitution for you?
You could then put the same `{(intVal)}` in the .json file.

Meanwhile feel free to join our Gitter chat for support: https://gitter.im/ctco/cukes-rest?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by AlexeyBuzdin** [comment]
Hi @aovercome1234. Investigated the DataTable approach you've proposed and identified a big issue with nested properties there.

If you want to construct a simple json ie `{ "name": "john"}` then DataTable will work fine. On the other hand if you want to create a nested object `{"name": {"firstname": "john", "lastname": "doe"}} then you'll be limited by Gherkin language. (here's a link to cucumber issue closed by the developers https://github.com/cucumber/cucumber-jvm/issues/442)

So supporting DataTables is a very low priority for cukes-rest since only a small portion of requests can be effectively written in such a way. I will close the issue but will reopen it once/if we decide to support DataTables at all.

But big thanks for bringing this up! If you have any other question on cukes-rest, please don't hesitate to write, would be glad to help.
