### ISSUE TITLE
Introduce Logger concept to cukes-rest

### ISSUE THREAD

**Issue by AlexeyBuzdin** [ctco/cukes-rest#37]
Logger should be introduced and all logs to be bridged there.

**Comment by berndgoetz** [comment]
Two additional information items should be logged per test: a) URL called, b) execution time of each step. Item b) is solved by introducing a reasonable logger format. Item a) is useful to right away see to which instance of my service that test connected to. Helpful if I have multiple instances, such as localhost, DEV, CI, SPRINT.

**Comment by jromero** [comment]
I recommend using SLF4 and allowing the applications which consume this library to use their existing logging library/implementation.

<a href="https://www.slf4j.org/images/legacy.png">
<img src="https://www.slf4j.org/images/legacy.png" width="500"/>
</a>

**Comment by jromero** [comment]
I've been working on this and there are a few things to note:

1. There is already support for logging via logback. Logging isn't as pretty since it's the *raw* wire. For example, if gzip encoded then you only see binary data. More details: https://hc.apache.org/httpcomponents-client-ga/logging.html
2. In the sample app, Dropwizard sets a LoggerFactory that then uses it's own configuration (yml)
3. Rest Assured has nice logging but needs to be injected into very specific sections of the DSL. After `when()` AND after `then()`. <s>`then()` is difficult because there are certain cases where we use `thenReturn()` to use custom assertions based on content type. I have not found a good way to log through Rest Assured when only retrieving the `ResponseBody`.</s>

**Comment by jromero** [comment]
@IgorGursky / @AlexeyBuzdin If I'm not mistaken this issue can be closed.

**Comment by IgorGursky** [comment]
Sure, you are right! Thanks for the notice!
